"""stage 1: coins, candles, ticker snapshots, system logs

Revision ID: 00078a29af46
Revises: 
Create Date: 2026-09-13 06:47:43.504294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Column types defined by this project (Money, UtcDateTime). Autogenerate
# renders them by dotted path, so the package must be importable here.
import app.database.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '00078a29af46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('open_time', app.database.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('open', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('high', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('low', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('close', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('volume', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('quote_volume', app.database.types.Money(precision=38, scale=18), nullable=True),
    sa.Column('trades', sa.Integer(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', app.database.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'open_time', name='uq_candle_series')
    )
    op.create_index('ix_candles_lookup', 'candles', ['symbol', 'timeframe', 'open_time'], unique=False)
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('base_asset', sa.String(length=16), nullable=False),
    sa.Column('quote_asset', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', app.database.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coins_active_sort', 'coins', ['is_active', 'sort_order'], unique=False)
    op.create_index(op.f('ix_coins_symbol'), 'coins', ['symbol'], unique=True)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', app.database.types.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_logs_lookup', 'system_logs', ['category', 'created_at'], unique=False)
    op.create_table('ticker_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('price', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('change_24h_pct', app.database.types.Money(precision=38, scale=18), nullable=True),
    sa.Column('high_24h', app.database.types.Money(precision=38, scale=18), nullable=True),
    sa.Column('low_24h', app.database.types.Money(precision=38, scale=18), nullable=True),
    sa.Column('volume_24h', app.database.types.Money(precision=38, scale=18), nullable=True),
    sa.Column('quote_volume_24h', app.database.types.Money(precision=38, scale=18), nullable=True),
    sa.Column('observed_at', app.database.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', app.database.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticker_symbol_time', 'ticker_snapshots', ['symbol', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticker_symbol_time', table_name='ticker_snapshots')
    op.drop_table('ticker_snapshots')
    op.drop_index('ix_system_logs_lookup', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_coins_symbol'), table_name='coins')
    op.drop_index('ix_coins_active_sort', table_name='coins')
    op.drop_table('coins')
    op.drop_index('ix_candles_lookup', table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
