"""stage 10: risk overrides

Revision ID: 8ab00a3c45a7
Revises: cc6ac000c336
Create Date: 2026-09-13 16:43:36.260164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Column types defined by this project (Money, UtcDateTime). Autogenerate
# renders them by dotted path, so the package must be importable here.
import app.database.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '8ab00a3c45a7'
down_revision: Union[str, Sequence[str], None] = 'cc6ac000c336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('baseline_equity', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('drawdown_pct_at_reset', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('at', app.database.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.database.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_overrides_at', 'risk_overrides', ['at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_overrides_at', table_name='risk_overrides')
    op.drop_table('risk_overrides')
    # ### end Alembic commands ###
