"""stage 6: paper trades and portfolio snapshots

Revision ID: cc6ac000c336
Revises: 00078a29af46
Create Date: 2026-09-13 07:16:01.495848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Column types defined by this project (Money, UtcDateTime). Autogenerate
# renders them by dotted path, so the package must be importable here.
import app.database.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'cc6ac000c336'
down_revision: Union[str, Sequence[str], None] = '00078a29af46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('entry', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('stop_loss', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('take_profit', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('quantity', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('notional', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('risk_amount', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('reward_risk', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('exit_price', app.database.types.Money(precision=38, scale=18), nullable=True),
    sa.Column('pnl', app.database.types.Money(precision=38, scale=18), nullable=True),
    sa.Column('pnl_pct', app.database.types.Money(precision=38, scale=18), nullable=True),
    sa.Column('r_multiple', app.database.types.Money(precision=38, scale=18), nullable=True),
    sa.Column('fees', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('confidence', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('opened_at', app.database.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('closed_at', app.database.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.database.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_trades_opened', 'paper_trades', ['opened_at'], unique=False)
    op.create_index('ix_paper_trades_status', 'paper_trades', ['status', 'symbol'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('equity', app.database.types.Money(precision=38, scale=18), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('at', app.database.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.database.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_snapshots_at', 'portfolio_snapshots', ['at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portfolio_snapshots_at', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index('ix_paper_trades_status', table_name='paper_trades')
    op.drop_index('ix_paper_trades_opened', table_name='paper_trades')
    op.drop_table('paper_trades')
    # ### end Alembic commands ###
